#
# This file is automatically generated from ripper.y.
# DO NOT MODIFY!!!!!!
#

require 'ripper.so'

class Ripper
  def self.parse( s, *args )
    new.parse s, *args
  end

  def on__AMPER( *args )
    args[0]
  end
  def on__AND( *args )
    args[0]
  end
  def on__ANDAND( *args )
    args[0]
  end
  def on__ANDAND_ASSIGN( *args )
    args[0]
  end
  def on__AND_ASSIGN( *args )
    args[0]
  end
  def on__AREF( *args )
    args[0]
  end
  def on__ASET( *args )
    args[0]
  end
  def on__ASSIGN( *args )
    args[0]
  end
  def on__ASSOC( *args )
    args[0]
  end
  def on__AT( *args )
    args[0]
  end
  def on__BACKQUOTE( *args )
    args[0]
  end
  def on__BACKSLASH( *args )
    args[0]
  end
  def on__BACK_REF( *args )
    args[0]
  end
  def on__BANG( *args )
    args[0]
  end
  def on__BEGIN( *args )
    args[0]
  end
  def on__CHAR( *args )
    args[0]
  end
  def on__CMP( *args )
    args[0]
  end
  def on__CMP_ASSIGN( *args )
    args[0]
  end
  def on__COLON( *args )
    args[0]
  end
  def on__COLON2( *args )
    args[0]
  end
  def on__COLON3( *args )
    args[0]
  end
  def on__COMMA( *args )
    args[0]
  end
  def on__CONSTANT( *args )
    args[0]
  end
  def on__CVAR( *args )
    args[0]
  end
  def on__DOLLER( *args )
    args[0]
  end
  def on__DOT( *args )
    args[0]
  end
  def on__DOT2( *args )
    args[0]
  end
  def on__DOT3( *args )
    args[0]
  end
  def on__END( *args )
    args[0]
  end
  def on__EQ( *args )
    args[0]
  end
  def on__EQQ( *args )
    args[0]
  end
  def on__FID( *args )
    args[0]
  end
  def on__GEQ( *args )
    args[0]
  end
  def on__GT( *args )
    args[0]
  end
  def on__GVAR( *args )
    args[0]
  end
  def on__HAT( *args )
    args[0]
  end
  def on__HAT_ASSIGN( *args )
    args[0]
  end
  def on__IDENTIFIER( *args )
    args[0]
  end
  def on__INTEGER_10( *args )
    args[0]
  end
  def on__INTEGER_16( *args )
    args[0]
  end
  def on__INTEGER_2( *args )
    args[0]
  end
  def on__INTEGER_8( *args )
    args[0]
  end
  def on__IVAR( *args )
    args[0]
  end
  def on__KEYWORD( *args )
    args[0]
  end
  def on__LBRACE( *args )
    args[0]
  end
  def on__LBRACE_ARG( *args )
    args[0]
  end
  def on__LBRACKET( *args )
    args[0]
  end
  def on__LPAREN( *args )
    args[0]
  end
  def on__LPAREN_ARG( *args )
    args[0]
  end
  def on__LSHIFT( *args )
    args[0]
  end
  def on__LT( *args )
    args[0]
  end
  def on__MATCH( *args )
    args[0]
  end
  def on__MINUS( *args )
    args[0]
  end
  def on__MINUS_ASSIGN( *args )
    args[0]
  end
  def on__MUL( *args )
    args[0]
  end
  def on__MUL_ASSIGN( *args )
    args[0]
  end
  def on__NEQ( *args )
    args[0]
  end
  def on__NMATCH( *args )
    args[0]
  end
  def on__NTH_REF( *args )
    args[0]
  end
  def on__OR( *args )
    args[0]
  end
  def on__OROR( *args )
    args[0]
  end
  def on__OROR_ASSIGN( *args )
    args[0]
  end
  def on__OR_ASSIGN( *args )
    args[0]
  end
  def on__PERCENT( *args )
    args[0]
  end
  def on__PERCENT_ASSIGN( *args )
    args[0]
  end
  def on__PLUS( *args )
    args[0]
  end
  def on__PLUS_ASSIGN( *args )
    args[0]
  end
  def on__POW( *args )
    args[0]
  end
  def on__Q( *args )
    args[0]
  end
  def on__RBRACE( *args )
    args[0]
  end
  def on__RBRACKET( *args )
    args[0]
  end
  def on__RPAREN( *args )
    args[0]
  end
  def on__RSHIFT( *args )
    args[0]
  end
  def on__RSHIFT_ASSIGN( *args )
    args[0]
  end
  def on__SEMICOLON( *args )
    args[0]
  end
  def on__SLASH( *args )
    args[0]
  end
  def on__SLASH_ASSIGN( *args )
    args[0]
  end
  def on__STAR( *args )
    args[0]
  end
  def on__SYMBEG( *args )
    args[0]
  end
  def on__TILDE( *args )
    args[0]
  end
  def on__UMINUS( *args )
    args[0]
  end
  def on__UPLUS( *args )
    args[0]
  end
  def on__add_eval_string( *args )
    args[0]
  end
  def on__add_space( *args )
    args[0]
  end
  def on__add_string( *args )
    args[0]
  end
  def on__add_word( *args )
    args[0]
  end
  def on__alias( *args )
    args[0]
  end
  def on__ambiguous_argument( *args )
    args[0]
  end
  def on__and( *args )
    args[0]
  end
  def on__aref( *args )
    args[0]
  end
  def on__argadd( *args )
    args[0]
  end
  def on__argadd_args( *args )
    args[0]
  end
  def on__argadd_assocs( *args )
    args[0]
  end
  def on__argadd_block( *args )
    args[0]
  end
  def on__argadd_opt( *args )
    args[0]
  end
  def on__argadd_rest( *args )
    args[0]
  end
  def on__argadd_star( *args )
    args[0]
  end
  def on__argadd_value( *args )
    args[0]
  end
  def on__argstart( *args )
    args[0]
  end
  def on__argvoid( *args )
    args[0]
  end
  def on__assign( *args )
    args[0]
  end
  def on__assignable( *args )
    args[0]
  end
  def on__assoc( *args )
    args[0]
  end
  def on__assoc_add( *args )
    args[0]
  end
  def on__assoc_list( *args )
    args[0]
  end
  def on__backref_error( *args )
    args[0]
  end
  def on__begin( *args )
    args[0]
  end
  def on__begin_block( *args )
    args[0]
  end
  def on__begin_brace( *args )
    args[0]
  end
  def on__begin_do( *args )
    args[0]
  end
  def on__block( *args )
    args[0]
  end
  def on__blockcall( *args )
    args[0]
  end
  def on__blockvar( *args )
    args[0]
  end
  def on__break( *args )
    args[0]
  end
  def on__call( *args )
    args[0]
  end
  def on__call_colon( *args )
    args[0]
  end
  def on__case( *args )
    args[0]
  end
  def on__class( *args )
    args[0]
  end
  def on__comment( *args )
    args[0]
  end
  def on__comment_start( *args )
    args[0]
  end
  def on__condexpr( *args )
    args[0]
  end
  def on__const_get( *args )
    args[0]
  end
  def on__def( *args )
    args[0]
  end
  def on__defined( *args )
    args[0]
  end
  def on__else( *args )
    args[0]
  end
  def on__elsif( *args )
    args[0]
  end
  def on__embdoc( *args )
    args[0]
  end
  def on__embdoc_begin( *args )
    args[0]
  end
  def on__embdoc_begin_label( *args )
    args[0]
  end
  def on__embdoc_end( *args )
    args[0]
  end
  def on__embdoc_end_label( *args )
    args[0]
  end
  def on__end_brace( *args )
    args[0]
  end
  def on__end_do( *args )
    args[0]
  end
  def on__ensure( *args )
    args[0]
  end
  def on__escaped_newline( *args )
    args[0]
  end
  def on__eval_string_begin( *args )
    args[0]
  end
  def on__eval_string_end( *args )
    args[0]
  end
  def on__fcall( *args )
    args[0]
  end
  def on__for( *args )
    args[0]
  end
  def on__here_document_end( *args )
    args[0]
  end
  def on__here_document_eos( *args )
    args[0]
  end
  def on__here_document_eos_term( *args )
    args[0]
  end
  def on__if( *args )
    args[0]
  end
  def on__if_mod( *args )
    args[0]
  end
  def on__ignored_newline( *args )
    args[0]
  end
  def on__infix( *args )
    args[0]
  end
  def on__is_dyna_regexp( *args )
    args[0]
  end
  def on__is_once_regexp( *args )
    args[0]
  end
  def on__is_xstring( *args )
    args[0]
  end
  def on__lhsadd_value( *args )
    args[0]
  end
  def on__list_add( *args )
    args[0]
  end
  def on__list_start( *args )
    args[0]
  end
  def on__local_count( *args )
    args[0]
  end
  def on__local_pop( *args )
    args[0]
  end
  def on__local_push( *args )
    args[0]
  end
  def on__massign( *args )
    args[0]
  end
  def on__mlhs_add( *args )
    args[0]
  end
  def on__mlhs_add_star( *args )
    args[0]
  end
  def on__mlhs_aset( *args )
    args[0]
  end
  def on__mlhs_attrset_colon( *args )
    args[0]
  end
  def on__mlhs_attrset_dot( *args )
    args[0]
  end
  def on__mlhs_paren( *args )
    args[0]
  end
  def on__mlhs_star( *args )
    args[0]
  end
  def on__mlhs_start( *args )
    args[0]
  end
  def on__module( *args )
    args[0]
  end
  def on__name( *args )
    args[0]
  end
  def on__new_array( *args )
    args[0]
  end
  def on__new_hash( *args )
    args[0]
  end
  def on__new_here_document( *args )
    args[0]
  end
  def on__new_regexp( *args )
    args[0]
  end
  def on__new_string( *args )
    args[0]
  end
  def on__new_words( *args )
    args[0]
  end
  def on__new_xstring( *args )
    args[0]
  end
  def on__newline( *args )
    args[0]
  end
  def on__next( *args )
    args[0]
  end
  def on__not( *args )
    args[0]
  end
  def on__notop( *args )
    args[0]
  end
  def on__opaset( *args )
    args[0]
  end
  def on__opassign( *args )
    args[0]
  end
  def on__opcallassign( *args )
    args[0]
  end
  def on__or( *args )
    args[0]
  end
  def on__paren( *args )
    args[0]
  end
  def on__redo( *args )
    args[0]
  end
  def on__regexp_end( *args )
    args[0]
  end
  def on__regexp_options( *args )
    args[0]
  end
  def on__rescue( *args )
    args[0]
  end
  def on__rescue_else( *args )
    args[0]
  end
  def on__rescue_mod( *args )
    args[0]
  end
  def on__retry( *args )
    args[0]
  end
  def on__return( *args )
    args[0]
  end
  def on__scan( *args )
    args[0]
  end
  def on__sclass( *args )
    args[0]
  end
  def on__sdef( *args )
    args[0]
  end
  def on__set_line( *args )
    args[0]
  end
  def on__space( *args )
    args[0]
  end
  def on__string_add_dstr( *args )
    args[0]
  end
  def on__string_concat( *args )
    args[0]
  end
  def on__string_end( *args )
    args[0]
  end
  def on__super( *args )
    args[0]
  end
  def on__symbol( *args )
    args[0]
  end
  def on__tPOW_ASSIGN( *args )
    args[0]
  end
  def on__toplevel_const_get( *args )
    args[0]
  end
  def on__unary( *args )
    args[0]
  end
  def on__undef( *args )
    args[0]
  end
  def on__unless( *args )
    args[0]
  end
  def on__unless_mod( *args )
    args[0]
  end
  def on__until( *args )
    args[0]
  end
  def on__until_mod( *args )
    args[0]
  end
  def on__varcall( *args )
    args[0]
  end
  def on__varref( *args )
    args[0]
  end
  def on__when( *args )
    args[0]
  end
  def on__while( *args )
    args[0]
  end
  def on__while_mod( *args )
    args[0]
  end
  def on__word_space( *args )
    args[0]
  end
  def on__words_end( *args )
    args[0]
  end
  def on__yield( *args )
    args[0]
  end
end
