:------------------------- WARNING ! ----------------------
:         This file is GENERATED by Instant Rails.
:
: If you need to make changes to this file, you should edit
: the source template file instead. The source template is
: E:\Dev\RubyDev\InstantRails-Project\trunk\InstantRails\conf_files\use_ruby.cmd
:-----------------------------------------------------------
CD E:\Dev\RubyDev\InstantRails-Project\trunk\InstantRails
PATH E:\Dev\RubyDev\InstantRails-Project\trunk\InstantRails\ruby\bin;E:\Dev\RubyDev\InstantRails-Project\trunk\InstantRails\mysql\bin;%PATH%
cd rails_apps
dir
