:------------------------- WARNING ! ----------------------
:         This file is GENERATED by Instant Rails.
:
: If you need to make changes to this file, you should edit
: the source template file instead. The source template is
: D:\OpenSourceProjects\InstantRails\InstantRails-win\InstantRails\conf_files\use_ruby.cmd
:-----------------------------------------------------------
CD D:\OpenSourceProjects\InstantRails\InstantRails-win\InstantRails
PATH D:\OpenSourceProjects\InstantRails\InstantRails-win\InstantRails\ruby\bin;D:\OpenSourceProjects\InstantRails\InstantRails-win\InstantRails\mysql\bin;%PATH%
cd rails_apps
dir
