
#pragma once

enum SERVER_STATE { SERVER_UNDEFINED = -1, SERVER_RUNNING = 0, SERVER_STOPPED = 1, SERVER_START_PENDING = 2, SERVER_STOP_PENDING = 3};

#define LOG_EASYPHP		0
#define LOG_MYSQL		1
#define LOG_APACHE		2
#define LOG_PHP			3
#define LOG_DEBUGGER	4
