//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EasyPhp.rc
//
#define ID_INSTALL                      101
#define IDR_MAINFRAME                   128
#define IDD_EASYPHP_DIALOG              133
#define IDD_ABOUT                       134
#define IDR_SOLEIL                      138
#define IDR_APACHE_ONLY_RUN             139
#define IDR_MYSQL_ONLY_RUN              140
#define IDR_MAINFRAME_LOIC              141
#define IDR_EASYPHP_LOIC                141
#define IDB_EASYPHP                     142
#define IDR_EASYPHP                     142
#define IDB_NOPIN                       164
#define IDB_PIN                         165
#define IDD_DEBUGGER                    170
#define IDB_BARRE                       173
#define IDB_HAUT                        181
#define IDB_HELP                        182
#define IDM_SERVEUR                     183
#define IDB_MINIMIZE                    183
#define IDM_START                       184
#define IDD_PHPEXT                      185
#define IDD_PREFERENCES                 186
#define IDB_ROUGE                       189
#define IDB_ORANGE                      190
#define IDB_VERT                        191
#define IDM_MAIN                        192
#define IDM_HELP                        193
#define IDM_MENU_SERVEURS               194
#define IDD_UPDATE                      195
#define IDD_SCGI                        196
#define IDC_CHECK_WINDOWSTART           1001
#define IDC_AUTOSERVEURSSTART           1002
#define IDC_CONFAUTORELOAD              1003
#define IDC_CHECK_SERVERS_PORT          1004
#define IDC_HOME_PAGE_LINK              1007
#define ID_ABOUT                        1008
#define IDC_LAURENT                     1009
#define IDC_EMMANUEL                    1010
#define IDC_THIERRY                     1011
#define ID_SHOW_ALWAYS                  1013
#define IDC_SSL                         1014
#define IDC_CHECK_EASYPHP_VERSION       1015
#define ID_CHECK_VERSION                1016
#define IDC_SERVICE                     1019
#define IDC_STATUS_MYSQL                1026
#define IDC_STATUS_APACHE               1027
#define IDE_MYSQL_ARGUMENTS             1031
#define ID_MENU                         1032
#define ID_PIN                          1040
#define IDL_PHP_EXTENSIONS              1048
#define IDL_RAILS_APPS_LIST             1048
#define ID_APACHE_SWITCH                1049
#define ID_MYSQL_SWITCH                 1050
#define IDC_BARRE                       1051
#define IDC_HAUT                        1052
#define IDC_LOG                         1054
#define ID_HELP_CONTEXT                 1059
#define ID_MINIMIZE                     1060
#define IDSL_VIEW                       1065
#define ID_OK                           1066
#define IDC_TITLE                       1067
#define ID_APACHE_MENU                  1071
#define ID_MYSQL_MENU                   1072
#define IDE_LICENCE                     1073
#define ID_VIEW_LICENCE                 1074
#define IDC_LANG                        1080
#define IDC_PRESENTATION                1081
#define IDC_SEE_SITE                    1082
#define IDC_MAIN_MYSQL_ARGUMENTS        1083
#define IDC_STATUS                      1084
#define IDC_EXT_ERROR_DEPENDANCE        1085
#define IDC_RA_MESSAGE                  1085
#define ID_APPLY_EXTENSIONS             1086
#define ID_REFRESH_EXTENSION            1087
#define IDC_BUTTON1                     1088
#define ID_PREFERENCES                  1088
#define ID_DEPENDS                      1088
#define IDC_EXPAND                      1088
#define ID_REFRESH_UPDATE               1088
#define ID_START_SCGI                   1088
#define IDC_PREFERENCES                 1089
#define ID_AUTOSTART_SCGI               1089
#define IDCB_APACHE                     1090
#define ID_CONFIG_SCGI                  1090
#define IDCB_MYSQL                      1091
#define IDC_LANGUAGE                    1091
#define ID_CONFIG_SCGI2                 1091
#define ID_OPEN_RAILS_CONSOLE           1091
#define IDC_TRANSLATED_BY               1092
#define ID_START_WEBRICK                1092
#define IDC_LIST1                       1093
#define IDL_UPDATEFILELIST              1093
#define ID_OPEN_RAILS_CONSOLE2          1093
#define ID_NEW_RAILS_APP                1093
#define IDC_UPDATE_MESSAGE              1094
#define ID_APPLY                        1095
#define IDC_PORT                        1097
#define IDC_CHECK1                      1098
#define IDC_AUTO_START                  1098
#define IDC_RUN_MODE                    1099
#define ID_EDIT_APACHE                  1100
#define ID_EDIT_HOSTS                   1101
#define IDC_SCGI_INSTRUCTIONS           1102
#define ID_START                        32771
#define IDS_START                       32771
#define ID_STOP                         32772
#define IDS_STOP                        32772
#define ID_APACHE_CONF                  32773
#define IDS_PENDING                     32773
#define ID_SWITCH                       32774
#define ID_HELP_CMDLINE                 32775
#define IDS_HELP_CMDLINE                32775
#define ID_QUIT                         32776
#define IDS_ERROR_MYSQL                 32779
#define ID_MYSQL_CONF                   32781
#define ID_APACHE_ERREUR_LOG            32782
#define IDS_DEFAULT_MYSQLARG            32782
#define ID_MYSQL_ERREUR_LOG             32783
#define IDS_ANOTHER_APACHE_RUN          32783
#define IDS_APACHE_ALREADY_RUN          32784
#define ID_BROWSE_WEB                   32785
#define ID_EASYPHP_CONF                 32786
#define IDS_APACHEMSG_UNEXPECTED_END    32787
#define IDS_PORT_OCCUPE                 32788
#define ID_PHP_CONF                     32788
#define IDS_SERVER_RUN_ERROR            32789
#define IDS_EXPERT_MODE_WARNING         32790
#define IDS_SWITCH_SSL                  32792
#define ID_CONFIGURATION_PHPEXT         32792
#define IDS_NEW_EASYPHP_VERSION         32793
#define ID_MYADMIN_CONF                 32793
#define ID_RESTART                      32794
#define IDS_RESTART                     32794
#define IDS_MYSQLMSG_UNEXPECTED_END     32795
#define ID_EASYPHP_LOG                  32796
#define IDS_STATE_STARTED               32796
#define ID_APACHE_ACCES_LOG             32797
#define IDS_STATE_STOPPED               32797
#define ID_AIDE_INTRO                   32798
#define IDS_HELPCTX_IDC_SERVICE         32798
#define ID_AIDE_FAQ                     32799
#define IDS_HELPCTX_NOHELP              32799
#define ID_AIDE_DEBUTER                 32800
#define IDS_ERROR_STOP_SERVER           32800
#define IDS_HELPCTX_IDC_CHECK_EASYPHP_VERSION 32801
#define ID_ADMINISTRATION               32801
#define IDS_HELPCTX_IDC_CONFAUTORELOAD  32802
#define IDS_HELPCTX_IDE_MYSQL_ARGUMENTS 32803
#define ID_EXPLORE_DOCROOT              32803
#define IDS_HELPCTX_IDC_AUTOSERVEURSSTART 32804
#define ID_SERVER_START                 32804
#define ID_SERVER_STOP                  32805
#define IDS_ERROR_RESTART_SERVER        32805
#define ID_SERVER_RESTART               32806
#define IDS_ERROR_INSTALL_SERVICE       32806
#define IDS_HELPCTX_IDC_STATUS_APACHE   32807
#define ID_SERVER_KILL                  32807
#define IDS_HELPCTX_IDC_STATUS_MYSQL    32808
#define ID_RESTART_APACHE               32808
#define IDS_HELPCTX_ID_PIN              32809
#define IDS_HELPCTX_ID_HELP_CONTEXT     32810
#define IDS_HELPCTX_IDSL_VIEW           32811
#define IDS_LOG_RESTART_SERVERS         32812
#define IDS_ERROR_APACHE_CONF           32813
#define IDS_LOG_CHANGE_CONF             32814
#define ID_FAKE                         32814
#define IDS_LOG_START_SERVERS           32815
#define ID_REGENERATE_CONF_FILES        32815
#define IDS_NOT_ADMIN                   32816
#define IDS_ERROR_BROWSER               32817
#define ID_EXPLORER_DOCROOTFORSTATICPAGES 32817
#define IDS_ERROR_REMOVE_SERVICE        32818
#define ID_WINDOWSEXPLORER_RAILSAPPLICATIONS 32818
#define IDS_SERVER_RESTART              32819
#define IDS_SERVER_KILL                 32820
#define ID_CONFIGURE_WINDOW             32820
#define IDS_ABOUT_TITLE                 32821
#define ID_NOTTOTRANSLATE_RAILSAPPLICATIONS 32821
#define IDS_ABOUT_VISIT_SITE            32822
#define IDS_ABOUT_SEE_LICENCE           32823
#define IDS_ABOUT_CHECK_VERSION         32824
#define ID_RAILSAPP_CONSOLE             32824
#define IDS_ABOUT_PRESENTATION          32825
#define ID_RAILSAPP_EXPLORER            32825
#define IDS_MAIN_STATUS                 32826
#define IDS_MAIN_CHECK_WINDOWSTART      32827
#define ID_MANAGERAILSAPPS              32827
#define IDS_MAIN_SERVICE                32828
#define IDS_MAIN_AUTOSERVEURSSTART      32829
#define IDS_MAIN_CHECK_EASYPHP_VERSION_AT_STARTUP 32830
#define ID_RELEASE_NOTES                32830
#define IDS_MAIN_CONFAUTORELOAD         32831
#define ID_HELP_FXRI                    32831
#define IDS_MAIN_MYSQL_ARGUMENTS        32832
#define IDS_MAIN_APPLIQUER              32833
#define IDS_MAIN_FERMER                 32834
#define IDS_MAIN_ABOUT                  32835
#define IDS_MENU_HELP                   32836
#define IDS_MENU_LOGFILES               32837
#define IDS_MENU_CONFIGURATION          32838
#define IDS_MENU_EXPLORE                32839
#define IDS_MENU_ADMINISTRATION         32840
#define IDS_MENU_WEBLOCAL               32841
#define IDS_MENU_QUIT                   32842
#define IDS_MENU_HELP_INTRODUCTION      32843
#define IDS_MENU_HELP_STARTPHP          32844
#define IDS_MENU_HELP_FAQ               32845
#define IDS_MENU_LOGFILES_APACHE_ERR    32846
#define IDS_MENU_LOGFILES_APACHE_ACCESS 32847
#define IDS_MENU_LOGFILES_MYSQLERR      32848
#define IDS_MENU_CONFIGURATION_EXTENSIONSPHP 32849
#define IDS_STARTPHP_URL                32850
#define IDS_MYSQL_LANGUAGE              32851
#define IDS_EXT_ERROR_DEPENDANCE        32852
#define IDS_RA_MESSAGE                  32852
#define IDS_REFRESH                     32853
#define IDS_LOG_STOP_SERVERS            32854
#define IDS_CONF_CHECK_SERVERS_PORT     32855
#define IDS_CONF_LANGUAGE               32856
#define IDS_CONF_PREFERENCES            32857
#define IDS_TRANSLATED_BY               32858
#define IDS_UPDATE_FILE                 32859
#define IDS_UPDATE_CURRENT_VERSION      32860
#define IDS_UPDATE_NEW_VERSION          32861
#define IDS_UPDATE_FILE_SIZE            32862
#define IDS_UPDATE_FILE_HASH            32863
#define IDS_UPDATE_WEB_FILE_ERROR       32864
#define IDS_UPDATE_HASH_DATA_ERROR      32865
#define IDS_UPDATE_UP_TO_DATE           32866
#define IDS_UPDATE_UPDATING             32867
#define IDS_UPDATE_BAD_HASH             32868
#define IDS_UPDATE_FILE_ERROR           32869
#define IDS_UPDATE_NEED_RESTART         32870
#define IDS_REMOVABLE_DRIVE             32871
#define IDS_PORT_OCCUPE_XP              32872
#define IDS_PROMPT_QUIT                 32874
#define IDS_ALWAYS_VISIBLE              32875
#define IDS_FOLDER_CHANGED              32876
#define IDS_CONFIG_SCGI                 32877

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        197
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
