Gem::Specification.new do |s|
  s.name = %q{activesupport}
  s.version = "1.2.3"
  s.date = %q{2005-11-06}
  s.summary = %q{Support and utility classes used by the Rails framework.}
  s.email = %q{david@loudthinking.com}
  s.homepage = %q{http://www.rubyonrails.org}
  s.rubyforge_project = %q{activesupport}
  s.description = %q{Utility library which carries commonly used classes and goodies from the Rails framework}
  s.has_rdoc = true
  s.authors = ["David Heinemeier Hansson"]
  s.files = ["CHANGELOG", "lib/active_support", "lib/active_support.rb", "lib/active_support/binding_of_caller.rb", "lib/active_support/breakpoint.rb", "lib/active_support/class_attribute_accessors.rb", "lib/active_support/class_inheritable_attributes.rb", "lib/active_support/clean_logger.rb", "lib/active_support/core_ext", "lib/active_support/core_ext.rb", "lib/active_support/dependencies.rb", "lib/active_support/inflections.rb", "lib/active_support/inflector.rb", "lib/active_support/module_attribute_accessors.rb", "lib/active_support/ordered_options.rb", "lib/active_support/values", "lib/active_support/version.rb", "lib/active_support/whiny_nil.rb", "lib/active_support/core_ext/array", "lib/active_support/core_ext/array.rb", "lib/active_support/core_ext/blank.rb", "lib/active_support/core_ext/cgi", "lib/active_support/core_ext/cgi.rb", "lib/active_support/core_ext/date", "lib/active_support/core_ext/date.rb", "lib/active_support/core_ext/enumerable.rb", "lib/active_support/core_ext/exception.rb", "lib/active_support/core_ext/hash", "lib/active_support/core_ext/hash.rb", "lib/active_support/core_ext/integer", "lib/active_support/core_ext/integer.rb", "lib/active_support/core_ext/kernel.rb", "lib/active_support/core_ext/load_error.rb", "lib/active_support/core_ext/numeric", "lib/active_support/core_ext/numeric.rb", "lib/active_support/core_ext/object_and_class.rb", "lib/active_support/core_ext/range", "lib/active_support/core_ext/range.rb", "lib/active_support/core_ext/string", "lib/active_support/core_ext/string.rb", "lib/active_support/core_ext/time", "lib/active_support/core_ext/time.rb", "lib/active_support/core_ext/array/conversions.rb", "lib/active_support/core_ext/cgi/escape_skipping_slashes.rb", "lib/active_support/core_ext/date/conversions.rb", "lib/active_support/core_ext/hash/indifferent_access.rb", "lib/active_support/core_ext/hash/keys.rb", "lib/active_support/core_ext/hash/reverse_merge.rb", "lib/active_support/core_ext/integer/even_odd.rb", "lib/active_support/core_ext/integer/inflections.rb", "lib/active_support/core_ext/numeric/bytes.rb", "lib/active_support/core_ext/numeric/time.rb", "lib/active_support/core_ext/range/conversions.rb", "lib/active_support/core_ext/string/access.rb", "lib/active_support/core_ext/string/conversions.rb", "lib/active_support/core_ext/string/inflections.rb", "lib/active_support/core_ext/string/starts_ends_with.rb", "lib/active_support/core_ext/time/calculations.rb", "lib/active_support/core_ext/time/conversions.rb", "lib/active_support/values/time_zone.rb"]
end
