Gem::Specification.new do |s|
  s.name = %q{actionmailer}
  s.version = "1.1.5"
  s.date = %q{2005-12-13}
  s.summary = %q{Service layer for easy email delivery and testing.}
  s.email = %q{david@loudthinking.com}
  s.homepage = %q{http://www.rubyonrails.org}
  s.rubyforge_project = %q{actionmailer}
  s.description = %q{Makes it trivial to test and deliver emails sent from a single service layer.}
  s.autorequire = %q{action_mailer}
  s.has_rdoc = true
  s.authors = ["David Heinemeier Hansson"]
  s.files = ["rakefile", "install.rb", "README", "CHANGELOG", "MIT-LICENSE", "lib/action_mailer", "lib/action_mailer.rb", "lib/action_mailer/adv_attr_accessor.rb", "lib/action_mailer/base.rb", "lib/action_mailer/helpers.rb", "lib/action_mailer/mail_helper.rb", "lib/action_mailer/part.rb", "lib/action_mailer/part_container.rb", "lib/action_mailer/quoting.rb", "lib/action_mailer/utils.rb", "lib/action_mailer/vendor", "lib/action_mailer/version.rb", "lib/action_mailer/vendor/text", "lib/action_mailer/vendor/tmail", "lib/action_mailer/vendor/tmail.rb", "lib/action_mailer/vendor/text/format.rb", "lib/action_mailer/vendor/tmail/address.rb", "lib/action_mailer/vendor/tmail/attachments.rb", "lib/action_mailer/vendor/tmail/base64.rb", "lib/action_mailer/vendor/tmail/config.rb", "lib/action_mailer/vendor/tmail/encode.rb", "lib/action_mailer/vendor/tmail/facade.rb", "lib/action_mailer/vendor/tmail/header.rb", "lib/action_mailer/vendor/tmail/info.rb", "lib/action_mailer/vendor/tmail/loader.rb", "lib/action_mailer/vendor/tmail/mail.rb", "lib/action_mailer/vendor/tmail/mailbox.rb", "lib/action_mailer/vendor/tmail/mbox.rb", "lib/action_mailer/vendor/tmail/net.rb", "lib/action_mailer/vendor/tmail/obsolete.rb", "lib/action_mailer/vendor/tmail/parser.rb", "lib/action_mailer/vendor/tmail/port.rb", "lib/action_mailer/vendor/tmail/quoting.rb", "lib/action_mailer/vendor/tmail/scanner.rb", "lib/action_mailer/vendor/tmail/scanner_r.rb", "lib/action_mailer/vendor/tmail/stringio.rb", "lib/action_mailer/vendor/tmail/tmail.rb", "lib/action_mailer/vendor/tmail/utils.rb", "test/fixtures", "test/mail_helper_test.rb", "test/mail_render_test.rb", "test/mail_service_test.rb", "test/quoting_test.rb", "test/tmail_test.rb", "test/fixtures/helper_mailer", "test/fixtures/helpers", "test/fixtures/raw_email", "test/fixtures/raw_email10", "test/fixtures/raw_email11", "test/fixtures/raw_email12", "test/fixtures/raw_email2", "test/fixtures/raw_email3", "test/fixtures/raw_email4", "test/fixtures/raw_email5", "test/fixtures/raw_email6", "test/fixtures/raw_email7", "test/fixtures/raw_email8", "test/fixtures/raw_email9", "test/fixtures/templates", "test/fixtures/test_mailer", "test/fixtures/helper_mailer/use_helper.rhtml", "test/fixtures/helper_mailer/use_helper_method.rhtml", "test/fixtures/helper_mailer/use_mail_helper.rhtml", "test/fixtures/helper_mailer/use_test_helper.rhtml", "test/fixtures/helpers/test_helper.rb", "test/fixtures/templates/signed_up.rhtml", "test/fixtures/test_mailer/implicitly_multipart_example.text.html.rhtml", "test/fixtures/test_mailer/implicitly_multipart_example.text.plain.rhtml", "test/fixtures/test_mailer/implicitly_multipart_example.text.yaml.rhtml", "test/fixtures/test_mailer/signed_up.rhtml"]
  s.requirements = ["none"]
  s.add_dependency(%q<actionpack>, ["= 1.11.2"])
end
