Gem::Specification.new do |s|
  s.name = %q{markaby}
  s.version = "0.3"
  s.date = %q{2006-02-01}
  s.summary = %q{Markup as Ruby, write HTML in your native Ruby tongue}
  s.has_rdoc = true
  s.authors = ["Tim Fletcher and _why"]
  s.files = ["README", "Rakefile", "setup.rb", "doc/rdoc", "doc/rdoc/created.rid", "doc/rdoc/rdoc-style.css", "doc/rdoc/files", "doc/rdoc/classes", "doc/rdoc/fr_file_index.html", "doc/rdoc/fr_class_index.html", "doc/rdoc/fr_method_index.html", "doc/rdoc/index.html", "doc/rdoc/files/README.html", "doc/rdoc/files/CHANGELOG.html", "doc/rdoc/files/lib", "doc/rdoc/files/lib/markaby_rb.html", "doc/rdoc/files/lib/markaby", "doc/rdoc/files/lib/markaby/metaid_rb.html", "doc/rdoc/files/lib/markaby/tags_rb.html", "doc/rdoc/files/lib/markaby/builder_rb.html", "doc/rdoc/files/lib/markaby/cssproxy_rb.html", "doc/rdoc/files/lib/markaby/view_rb.html", "doc/rdoc/files/lib/markaby/template_rb.html", "doc/rdoc/files/lib/markaby/helper_rb.html", "doc/rdoc/classes/Object.src", "doc/rdoc/classes/Markaby", "doc/rdoc/classes/Object.html", "doc/rdoc/classes/Markaby.html", "doc/rdoc/classes/Object.src/M000001.html", "doc/rdoc/classes/Object.src/M000002.html", "doc/rdoc/classes/Object.src/M000003.html", "doc/rdoc/classes/Object.src/M000004.html", "doc/rdoc/classes/Markaby/ActionControllerHelper.src", "doc/rdoc/classes/Markaby/CssProxy.src", "doc/rdoc/classes/Markaby/Builder.src", "doc/rdoc/classes/Markaby/Template.src", "doc/rdoc/classes/Markaby/View.src", "doc/rdoc/classes/Markaby/ActionControllerHelper.html", "doc/rdoc/classes/Markaby/CssProxy.html", "doc/rdoc/classes/Markaby/Builder.html", "doc/rdoc/classes/Markaby/Template.html", "doc/rdoc/classes/Markaby/View.html", "doc/rdoc/classes/Markaby/ActionControllerHelper.src/M000005.html", "doc/rdoc/classes/Markaby/CssProxy.src/M000006.html", "doc/rdoc/classes/Markaby/CssProxy.src/M000007.html", "doc/rdoc/classes/Markaby/Builder.src/M000008.html", "doc/rdoc/classes/Markaby/Builder.src/M000009.html", "doc/rdoc/classes/Markaby/Builder.src/M000010.html", "doc/rdoc/classes/Markaby/Builder.src/M000012.html", "doc/rdoc/classes/Markaby/Builder.src/M000013.html", "doc/rdoc/classes/Markaby/Builder.src/M000014.html", "doc/rdoc/classes/Markaby/Builder.src/M000015.html", "doc/rdoc/classes/Markaby/Builder.src/M000016.html", "doc/rdoc/classes/Markaby/Builder.src/M000017.html", "doc/rdoc/classes/Markaby/Builder.src/M000018.html", "doc/rdoc/classes/Markaby/Builder.src/M000019.html", "doc/rdoc/classes/Markaby/Builder.src/M000021.html", "doc/rdoc/classes/Markaby/Template.src/M000022.html", "doc/rdoc/classes/Markaby/Template.src/M000023.html", "doc/rdoc/classes/Markaby/View.src/M000024.html", "doc/rdoc/classes/Markaby/View.src/M000025.html", "test/test_markaby.rb", "test/example.rb", "lib/markaby", "lib/markaby.rb", "lib/markaby/metaid.rb", "lib/markaby/tags.rb", "lib/markaby/builder.rb", "lib/markaby/cssproxy.rb", "lib/markaby/view.rb", "lib/markaby/template.rb", "lib/markaby/helper.rb", "tools/rakehelp.rb"]
  s.test_files = ["test/test_markaby.rb"]
  s.extra_rdoc_files = ["README"]
  s.add_dependency(%q<builder>, ["> 0.0.0"])
end
